### ISSUE TITLE
Custom songs no longer work when outputting to midi device

### ISSUE THREAD

**Issue by KieranGreenwood** [Bewelge/MIDIano#40] opened 2023-11-16 23:31 UTC
Steps to reproduce:
1. enable midi output to piano
2. load custom song
3. play

The animation plays to the first note and crashes before it starts.

This behavior only seems to happen for custom songs that try to output to midi device.

- The default preloaded songs work and output to both pc speakers and midi device speakers.
- Custom songs work and output via pc speakers just not midi.

Once a custom song has crashed the app, all other types of song no longer work until the app is refreshed.

The following error logs as it crashes:
```
main.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'timestamp')
    at t.playSustain (main.min.js:1:821556)
    at t.playNotesTick (main.min.js:1:819037)
    at t.playTick (main.min.js:1:818129)
    at main.min.js:1:820196
```

**Comment by Bewelge** [comment] 2023-11-17 06:36
Thanks for the notice! It was caused by songs that contain no sustain events, since I recently added sustain to MIDI out. Should be fixed now.

**Closed as completed by Bewelge** 2023-11-17 06:36 UTC
